export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const RECEIVE_SONGS_SUCCESS = 'RECEIVE_SONGS_SUCCESS';
export const RECEIVE_SONGS_FAIL = 'RECEIVE_SONGS_FAIL';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const RECEIVE_COMMENTS_SUCCESS = 'RECEIVE_COMMENTS_SUCCESS';
export const RECEIVE_COMMENTS_FAIL = 'RECEIVE_COMMENTS_FAIL';
export const SEND_COMMENT = 'SEND_COMMENT';

export const SEND_AUTH_REQUEST = 'SEND_AUTH_REQUEST';
export const RECEIVE_AUTH_SUCCESS = 'RECEIVE_AUTH_SUCCESS';
export const RECEIVE_AUTH_FAIL = 'RECEIVE_AUTH_FAIL';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const RECEIVE_USERS_SUCCESS = 'RECEIVE_USERS_SUCCESS';
export const RECEIVE_USERS_FAIL = 'RECEIVE_USERS_FAIL';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const RECEIVE_ADD_USER_SUCCESS = 'RECEIVE_ADD_USER_SUCCESS';
export const RECEIVE_ADD_USER_FAIL = 'RECEIVE_ADD_USER_FAIL';
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const RECEIVE_EDIT_USER_SUCCESS = 'RECEIVE_EDIT_USER_SUCCESS';
export const RECEIVE_EDIT_USER_FAIL = 'RECEIVE_EDIT_USER_FAIL';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const RECEIVE_DELETE_USER_SUCCESS = 'RECEIVE_DELETE_USER_SUCCESS';
export const RECEIVE_DELETE_USER_FAIL = 'RECEIVE_DELETE_USER_FAIL';
export const CLEAR_ADD_MESSAGES = 'CLEAR_ADD_MESSAGES';

export const SEND_LIKE_REQUEST = 'SEND_LIKE_REQUEST';
export const RECEIVE_LIKE_SUCCESS = 'RECEIVE_LIKE_SUCCESS';
export const RECEIVE_LIKE_FAIL = 'RECEIVE_LIKE_FAIL';

export const SEND_LOGOUT_REQUEST = 'SEND_LOGOUT_REQUEST';

export const SEND_REG_REQUEST = 'SEND_REG_REQUEST';
export const RECEIVE_REG_SUCCESS = 'RECEIVE_REG_SUCCESS';
export const RECEIVE_REG_FAIL = 'RECEIVE_REG_FAIL';

export const CLEAR_LOGIN_REG_MESSAGES = 'CLEAR_LOGIN_REG_MESSAGES';

export const SERVER_CONNECTION_ERROR = 'SERVER_CONNECTION_ERROR';

export const OPEN_PLAYER = 'OPEN_PLAYER';
export const CLOSE_PLAYER = 'CLOSE_PLAYER';
export const PLAY_SONG = 'PLAY_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const NEXT_SONG = 'NEXT_SONG';
export const PREVIOUS_SONG = 'PREVIOUS_SONG';
export const TURN_ON_FIRST_SONG = 'TURN_ON_FIRST_SONG';
export const TURN_ON_LAST_SONG = 'TURN_ON_LAST_SONG';
export const INC_COUNT = 'INC_COUNT';
export const OPEN_DIALOG_TRACK = 'OPEN_DIALOG_TRACK';
export const CLOSE_DIALOG_TRACK = 'CLOSE_DIALOG_TRACK';
export const OPEN_UPLOAD_CHANGE_DIALOG_TRACK = 'OPEN_UPLOAD_CHANGE_DIALOG_TRACK';
export const CLOSE_UPLOAD_CHANGE_DIALOG_TRACK = 'CLOSE_UPLOAD_CHANGE_DIALOG_TRACK';
export const UPLOAD_TRACK = 'UPLOAD_TRACK';
export const RECEIVE_UPLOAD_TRACK_SUCCESS = 'RECEIVE_UPLOAD_TRACK_SUCCESS';
export const RECEIVE_UPLOAD_TRACK_FAIL = 'RECEIVE_UPLOAD_TRACK_FAIL';
export const CLEAR_MESSAGE_UPLOAD = 'CLEAR_MESSAGE_UPLOAD';
export const DELETE_TRACK = 'DELETE_TRACK';
export const RECEIVE_DELETE_TRACK_SUCCESS = 'RECEIVE_DELETE_TRACKK_SUCCESS';
export const RECEIVE_DELETE_TRACK_FAIL = 'RECEIVE_DELETE_TRACK_FAIL';
